import type { Metadata } from "next";
import Headbar from "@/app/components/HeadBar";
import Footer from "@/app/components/Footer";
import ChatWidget from "@/app/components/ChatWidget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Headbar />
      <div className="mt-28">
        {children}
        <Footer />
        <ChatWidget />
      </div>
    </div>

  );
}