import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@flaticon/flaticon-uicons/css/all/all.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bakh = localFont({
  src: [
    {
      path: "./fonts/YekanBakhFaNum-Bold.woff",
      weight: "700",

      style: "bold",
    },
    {
      path: "./fonts/YekanBakhFaNum-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/YekanBakhFaNum-ExtraBlack.woff",
      weight: "900",
      style: "black",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${bakh.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
